// Code generated by "stringer -type=EventType"; DO NOT EDIT

package dokku

import "fmt"

const _EventType_name = "PreDeployPostDeployCheckDeployPreDeletePostDeleteRecieveAppPostDomainsUpdate"

var _EventType_index = [...]uint8{0, 9, 19, 30, 39, 49, 59, 76}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
