// Code generated by "stringer -type=AppStatus"; DO NOT EDIT

package models

import "fmt"

const _AppStatus_name = "RunningStoppedUndeployed"

var _AppStatus_index = [...]uint8{0, 7, 14, 24}

func (i AppStatus) String() string {
	if i < 0 || i >= AppStatus(len(_AppStatus_index)-1) {
		return fmt.Sprintf("AppStatus(%d)", i)
	}
	return _AppStatus_name[_AppStatus_index[i]:_AppStatus_index[i+1]]
}
